# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
fail_fast: True

repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        stages: [ commit ]
        language: system
        entry: pytest
        types: [ python ]
        pass_filenames: False #no filenames will be passed to the hook, run once
        args: [ -n, auto, --cov, --durations, "3"] # using forks - it's currently faster ~>20sec than n=1 (on linux)
        verbose: True
